// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChin9pxU8ipdVH2wRO8r5pWSTz6YIz8p8',
    appId: '1:626424575239:web:0617e5259e6fdb3ffb41a2',
    messagingSenderId: '626424575239',
    projectId: 'flutterchatapp-492f0',
    authDomain: 'flutterchatapp-492f0.firebaseapp.com',
    storageBucket: 'flutterchatapp-492f0.appspot.com',
    measurementId: 'G-NLH7Z72TWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCho3SXuPhk5fshQFdXUOtSFyCCnbGGkj0',
    appId: '1:626424575239:android:49ab3a912c00efe5fb41a2',
    messagingSenderId: '626424575239',
    projectId: 'flutterchatapp-492f0',
    storageBucket: 'flutterchatapp-492f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcAjiVzXykwi7DZUGBUdHGNhgYgFlOl4M',
    appId: '1:626424575239:ios:b1ebada5420221b4fb41a2',
    messagingSenderId: '626424575239',
    projectId: 'flutterchatapp-492f0',
    storageBucket: 'flutterchatapp-492f0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcAjiVzXykwi7DZUGBUdHGNhgYgFlOl4M',
    appId: '1:626424575239:ios:7b5db876716c4cc6fb41a2',
    messagingSenderId: '626424575239',
    projectId: 'flutterchatapp-492f0',
    storageBucket: 'flutterchatapp-492f0.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
